name: Publish Terraform Module 
 
on:
  push:
    #tags:
     # - 'v1.0.0' # Trigger on version tags like v1.0.0 

jobs:
  publish:
    name: Publish Terraform Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"    

      - name: Configure Git
        run: |
          git config --global url."https://${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Validate Terraform Module
        run: terraform init          

      - name: Validate Terraform Module
        run: terraform validate

      - name: Format Terraform Files
        run: terraform fmt -check

      - name: Publish Module
        run: |
          echo "Module version $(git describe --tags) published."
